# Generated by Django 4.2 on 2023-08-01 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('current_stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('offer_price', models.PositiveIntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.category')),
            ],
        ),
    ]
