# Generated by Django 4.2 on 2023-08-08 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_alter_product_table'),
        ('administrator', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.customer')),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.product')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
