# Generated by Django 4.2 on 2023-08-17 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_product_table'),
        ('administrator', '0002_customer'),
        ('customer', '0002_rename_price_cart_sub_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=1000)),
                ('place', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.customer')),
            ],
            options={
                'db_table': 'orderAddress',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=25, unique=True)),
                ('order_no', models.CharField(max_length=40)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('payment_id', models.CharField(max_length=25, null=True, unique=True)),
                ('signature_id', models.CharField(max_length=25, null=True, unique=True)),
                ('order_status', models.CharField(max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.customer')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.deliveryaddress')),
            ],
            options={
                'db_table': 'order_tb',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.product')),
            ],
            options={
                'db_table': 'orderItem_tb',
            },
        ),
    ]
