# Generated by Django 4.2 on 2023-08-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_deliveryaddress_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveryaddress',
            table='DeliveryAddress',
        ),
    ]
