# Generated by Django 4.2 on 2023-08-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_deliveryaddress_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveryaddress',
            table='delivery_address',
        ),
    ]
