# Generated by Django 4.2 on 2023-08-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_deliveryaddress_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
